remote_theme: mmistakes/minimal-mistakes
title: About Me
include: ["_pages"]

author:
  name: "Ella Wells"
  avatar: "https://www.jdextravaganza.com/wp-content/uploads/2016/01/Dancer-1-Wide.png"
  bio: My name is Ella Wells. I am a competitive dancer, i also recently joined lacrosse at school.
