remote_theme: mmistakes/minimal-mistakes
title: About Me
include: ["_pages"]

author:
  name: "Ella Wells"
  avatar: "https://drive.google.com/file/d/0B0KGVOa_jvf9SGYtWnU0YS1KYWRGMi1uSHJjNTRfeVk5OHNJ/view?usp=sharing"
  bio: I am a freshman in High School.  An "A" Student
