remote_theme: mmistakes/minimal-mistakes
title: "MY LIFE: Ella Wells"
include: ["_pages"]

author:
  name: "Ella Wells"
  avatar: "http://www.utahdanceacademy.com/uploads/6/8/2/6/6826294/2325223_orig.png"
  bio: I am a freshman in High School.  An "A" Student, I play lacrosse, and I'm also a competitive dancer!
