remote_theme: mmistakes/minimal-mistakes
title: About Me
include: ["_pages"]

author:
  name: "Ella Wells"
  avatar: "https://www.jdextravaganza.com/wp-content/uploads/2016/01/Dancer-1-Wide.png"
  bio: I am a freshman in High School. 
  bio: - A student
  bio: - Womens Lacrosse player
  bio: - Competitive Dancer
